1、numpy
2、padas
3、matplotlib

### numpy

数字跟列表，列表可以存储任意类型的数据，而数组只能存储一种类型的数据

In [3]:
import array

In [4]:
a = array.array('i',range(10))

In [5]:
a[1]

1

In [6]:
a[0]

0

In [7]:
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
import numpy as np

#### 从原有列表转化为数组

In [9]:
a_list = list(range(10))
b = np.array(a_list)
type(b)

numpy.ndarray

#### 生成数组

In [10]:
from numpy import int64

In [11]:
a = np.zeros(10,dtype=int64)
print(type(a))
#查看数组类型
print(a.dtype)
a

<type 'numpy.ndarray'>
int64


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
a = np.zeros((4,4),dtype=int)
print(type(a))
#查看数组类型
print(a.dtype)
a

<type 'numpy.ndarray'>
int32


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones((4,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.full((3,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [15]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.full_like(a,4.12,dtype=float)

array([[4.12, 4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12, 4.12]])

### random

In [18]:
import random
print (random.randint(5,10))
random.random()

10


0.28476246649937664

In [19]:
np.random.random((3,3))

array([[0.09779573, 0.33460767, 0.59340176],
       [0.85429352, 0.28539694, 0.8624826 ],
       [0.22468411, 0.88351941, 0.25128708]])

In [20]:
np.random.randint(0,10,(5,5))

array([[7, 0, 4, 0, 2],
       [6, 2, 2, 3, 8],
       [7, 6, 6, 3, 8],
       [7, 6, 8, 5, 5],
       [9, 9, 0, 3, 1]])

In [21]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
#经常用到
np.linspace(0,3,11)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. ])

In [24]:
# n维的单位矩阵
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

|序号|数据类型及描述|
|:----|:--------------|
|1.  |bool_存储为一个字节的布尔值(真或假)|
|2.  |int_默认整数，相当于 C 的long，通常为int32或int64|
|3.  |intc相当于 C 的int，通常为int32或int64|
|4.  |intp用于索引的整数，相当于 C 的size_t，通常为int32或int64|
|5.  |int8字节(-128 ~ 127)|
|6.  |int1616 位整数(-32768 ~ 32767)|
|7.  |int3232 位整数(-2147483648 ~ 2147483647)|
|8.  |int6464 位整数(-9223372036854775808 ~ 9223372036854775807)|
|9.  |uint88 位无符号整数(0 ~ 255)|
|10. |uint1616 位无符号整数(0 ~ 65535)|
|11. |uint3232 位无符号整数(0 ~ 4294967295)|
|12. |uint6464 位无符号整数(0 ~ 18446744073709551615)|
|13. |float_float64的简写|
|14. |float16半精度浮点：符号位，5 位指数，10 位尾数|
|15. |float32单精度浮点：符号位，8 位指数，23 位尾数|
|16. |float64双精度浮点：符号位，11 位指数，52 位尾数|
|17. |complex_complex128的简写|
|18. |complex64复数，由两个 32 位浮点表示(实部和虚部)|
|19. |complex128复数，由两个 64 位浮点表示(实部和虚部)

In [25]:
!python --version 

Python 3.6.4 :: Anaconda, Inc.


In [26]:
current_path = %pwd
current_path

u'C:\\Users\\Administrator\\Desktop\\notebook'

### 访问数组中元素

In [27]:
#嵌套列表的元素访问
var =[[1,2,3],[3,4,5],[5,6,7]]
var[0][0]

1

In [54]:
a = np.full((3,3),9.9,dtype=float)
a=np.array(var)
print(type(a))
print (a.dtype)
a

<type 'numpy.ndarray'>
int32


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [29]:
a[-1][0]==a[-1,0]

True

In [30]:
# 数组切片
a[:2,:2]

array([[1, 2],
       [3, 4]])

In [31]:
a[:2,:2]==a[:2][:2]

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [32]:
# 纬度
print(a.ndim)
#shape
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

2
(3L, 3L)
9
int32
4
36


### 运算

In [33]:
a=np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
print(a+10)

[10 11 12 13 14 15 16 17 18 19]


In [35]:
a+10==np.add(a,10)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
sum([1,2,2,3])

8

### 统计类型

In [37]:
# 求和
a=np.full(10,2.3)
print(a)
print(sum(a))
# 数组多维求和
a=np.array([[1,2],[3,4]])
np.sum(a,axis=1)
np.max(a,axis=1)

[2.3 2.3 2.3 2.3 2.3 2.3 2.3 2.3 2.3 2.3]
23.000000000000004


array([2, 4])

In [38]:
n=np.random.rand(10000)
print(n)

[0.09073433 0.57103469 0.61573173 ... 0.65226457 0.61370893 0.19089986]


### notebook 使用小技巧
%timeit 代码；此方法来判断程序的执行效率

In [39]:
%timeit sum(n)

1000 loops, best of 3: 1.75 ms per loop


In [40]:
%timeit np.sum(n)

The slowest run took 6.49 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.4 µs per loop


### 由此代码可以看出np.sum的执行效率高，推荐使用

### 比较

In [41]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
a!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [44]:
a==a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [45]:
np.all(a>-1)

True

In [46]:
np.equal(a,a)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [47]:
### 变形

In [59]:
a=np.full((2,10),1,dtype=float)
print(a)
print(a.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
float64


In [60]:
a.size

20

In [61]:
a.ndim

2

In [62]:
a.reshape(10,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
### 排序
l=[
    [1,2,3],
    [34,12,4],
    [32,2,33]
    ]
a=np.array(l)

In [56]:
np.sort(a)

array([[ 1,  2,  3],
       [ 4, 12, 34],
       [ 2, 32, 33]])

### 拼接